"""init migrate

Revision ID: 9a1732560847
Revises: 
Create Date: 2024-08-10 17:12:49.884332

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9a1732560847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'url_map',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('original', sa.String(length=1000), nullable=True),
        sa.Column('short', sa.String(length=16), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('short'),
    )
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_url_map_timestamp'), ['timestamp'], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_map_timestamp'))

    op.drop_table('url_map')
    # ### end Alembic commands ###
